adra/urls.py
from django.urls import path, include
from .views import (
    PersonaDetailView,
    PersonaCreateView,
    PersonaUpdateView, PersonaDeleteView,
    PersonaAlimentosDeleteView,
    AlmacenListView,
    HijoUpdateView,
    HijoDeleteView,
    PersonaListView,
    PersonaAlimentosUpdateView,
    statistics_persona,
    export_users_csv

)
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views as vs

app_name = 'adra'
# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'personas', views.PersonaViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
    path('api/', include((router.urls, 'api'), namespace='api')),
    path('api-token-auth/', vs.obtain_auth_token, name="api-token-auth"),
    # API
    # path('api/', views.api_root),
    # path('api/persona/', persona_list, name="persona-list"),
    # path('api/persona/<int:pk>/', persona_detail, name='persona-api-detail'),
    # path('api/users/', user_list, name='user-list'),
    # path('api/users/<int:pk>/', user_detail),

    # personas url
    path('', PersonaListView.as_view(), name="persona-home"),
    path('persona/<int:pk>/', PersonaDetailView.as_view(), name="personas_detail"),
    path('persona/new/', PersonaCreateView.as_view(), name="persona-create"),
    path('persona/<int:pk>/update/', PersonaUpdateView.as_view(),
         name="persona-update"),
    path('persona/<int:pk>/delete/', PersonaDeleteView.as_view(),
         name="persona-delete"),
    # end persona url

    # almacen url
    path('almacen/', AlmacenListView.as_view(), name="almacen-home"),
    # end almacen url

    # statistics
    path('statistics/', views.statistics_persona, name="statistics-personas"),
    path('telegram/', views.telegram_messages, name="telegram_message_view"),
    path('gastos/', views.gastos_delegacion, name="gastos_delegacion_view"),
    path('export/csv/', views.export_users_csv, name='exportar-users-csv'),
    path('export/pdf/<int:pk>', views.generar_hoja_entrega, name='pdf_form'),
    path('export/docx/<int:pk>', views.generar_hoja_valoracion_social, name='docx_form'),
    # end statistics

    # buscar url
    path('buscar/', views.buscar, name="buscar"),
    path('buscar_por_fecha/', views.buscar_fecha, name='buscar-por-fecha'),
    # end bucar url

    # alimentos url
    path('persona/<int:pk>/alimentos', views.adauga_alimentos_persona,
         name="alimentos-create"),
    path('persona/alimentos/<int:pk>/update',
         PersonaAlimentosUpdateView.as_view(), name='persona-update-alimentos'),

    path('persona/alimentos/<int:pk>/delete',
         PersonaAlimentosDeleteView.as_view(), name='persona-alimentos-delete'),
    # end alimentos url

    # hijos url
    path('persona/<int:pk>/hijos', views.adauga_hijo_persona,
         name="hijo-create"),
    path('persona/hijos/<int:pk>/update', HijoUpdateView.as_view(),
         name="hijo-update"),
    path('persona/hijos/<int:pk>/delete', HijoDeleteView.as_view(),
         name="hijo-delete"),
    # end hijos url
    path('edit/', views.edit, name='edit-profile'),
    path('get-data/', views.get_data, name='get_data'),
    path('adra-anuncios/', views.anuncios, name='anuncio'),

]
urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]

adra_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Django admin
    path('toate-dar-admin/', admin.site.urls),
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),

    # User management
    path('accounts/', include('allauth.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # local apps
    # path('accounts/', include('users.urls')),
    path('', include('adra.urls', namespace="adra")),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adra/forms.py
from django import forms
from .models import Persona, Alimentos, Hijo, Gasto
from django.contrib.auth.models import User
from django.forms import ModelForm, DateInput, EmailInput, Form, DateTimeInput


class AlimentosFrom(ModelForm):
    class Meta:
        model = Alimentos
        fields = (
            'alimento_1',
            'alimento_2',
            'alimento_3',
            'alimento_4',
            'alimento_6',
            'alimento_7',
            'alimento_8',
            'alimento_9',
            'alimento_10',
            'alimento_11',
            'alimento_12',
            'alimento_13',
            'alimento_14',
            'alimento_15',
            'fecha_recogida'
        )
        widgets = {
            'fecha_recogida': DateInput(attrs={"type": "date"}),
        }


class PersonaForm(ModelForm):
    class Meta:
        model = Persona
        fields = [
            'nombre_apellido',
            'dni',
            'otros_documentos',
            'fecha_nacimiento',
            'numero_adra',
            'nacionalidad',
            'domicilio',
            'are_acte',
            'ciudad',
            'telefono',
            'mensaje',
            'sexo',
            'discapacidad',
            'domingo',
            'empadronamiento',
            'libro_familia',
            'fotocopia_dni',
            'prestaciones',
            'nomnia',
            'cert_negativo',
            'aquiler_hipoteca',
            'recibos',
            'email',
            'covid',

        ]
        widgets = {
            'fecha_nacimiento': DateInput(attrs={"type": "date"}),
            'email': EmailInput(attrs={"type": "email"})
        }


class HijoForm(ModelForm):
    class Meta:
        model = Hijo
        fields = [
            'parentesco',
            'nombre_apellido',
            'dni',
            'otros_documentos',
            'fecha_nacimiento',

        ]
        widgets = {
            'fecha_nacimiento': DateInput(attrs={"type": "date"}),
        }


class GastoForm(ModelForm):
    class Meta:
        model = Gasto
        fields = [
            'concepto',
            'fecha',
            'importe',
            'tipo',
        ]
        widgets = {
            'fecha': DateInput(attrs={'type': 'date'}),
        }


class UserEditForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


# class ProfileEditForm(ModelForm):
#     class Meta:
#         model = Profile
#         fields = ('date_of_birth',)
#         widgets = {
#             'date_of_birth': DateInput(attrs={"type": "text"}),
#         }


class SignupForm(Form):
    first_name = forms.CharField(max_length=30, label='Nume')
    last_name = forms.CharField(max_length=30, label='Prenume')

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

adra/views.py
import io
import os
import time
from datetime import date
from decimal import Decimal

import telegram
import xlsxwriter
from PyPDF2 import PdfFileReader, PdfFileWriter
from PyPDF2.generic import BooleanObject, NameObject, IndirectObject
from allauth.account.adapter import DefaultAccountAdapter
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.db.models import Sum
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (ListView, DetailView, DeleteView, UpdateView, CreateView)
from mailmerge import MailMerge
from openpyxl import Workbook
from openpyxl.styles import Alignment, PatternFill
from rest_framework import permissions
from rest_framework import viewsets
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import (Mail)
# from .tasks import export_zip, delete_folder
from tenant_schemas.utils import remove_www
from .filters import AlimentosFilters
from .forms import AlimentosFrom, HijoForm, PersonaForm, UserEditForm, GastoForm
from .models import Persona, Alimentos, AlmacenAlimentos, Hijo, DelegacionData, Gasto
from .serializers import PersonaSerializer, UserSerializer
from shared.models import BeneficiariosGlobales


# from django.views.decorators.cache import cache_page

# logger = logging.getLogger(__name__)


def anuncios(request):
    return render(request, 'adra/anuncio.html')


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        # profile_form = ProfileEditForm(
        #     instance=request.user.profile,
        #     data=request.POST,
        #     files=request.FILES)
        # and profile_form.is_valid()
        if user_form.is_valid():
            user_form.save()
            # profile_form.save()
            messages.success(
                request, 'El perfil se ha actualizado correctamente')
            return redirect('adra:edit-profile')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        # profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'account/edit-perfile.html',
                  {'user_form': user_form})


class PersonaListView(LoginRequiredMixin, ListView):
    template_name = 'adra/index.html'
    context_object_name = 'ultima_persona'
    model = Persona
    paginate_by = 15
    login_url = 'account_login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # enviar al misma pagina varios contextos
        context['hijo'] = Hijo.objects
        context['hijomenor'] = Hijo
        context['nbar'] = "home"
        dels = DelegacionData.objects.first()
        self.request.session['platform_name'] = str(self.request.tenant)
        if dels.telegram_code:
            self.request.session['telegram_active'] = dels.telegram_code

        return context


# ir a la pagina detallada de cada persona
class PersonaDetailView(LoginRequiredMixin, DetailView):
    model = Persona
    template_name = 'adra/detail.html'
    context_object_name = 'persona'
    login_url = 'account_login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = AlimentosFilters(self.request.GET,
                                             queryset=self.get_queryset())
        return context


class BuscarDetailView(LoginRequiredMixin, ListView):
    model = Alimentos
    template_name = 'busqueda_a/view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = AlimentosFilters(self.request.GET,
                                             queryset=self.get_queryset())
        return context


class PersonaCreateView(LoginRequiredMixin, CreateView):
    model = Persona
    success_url = '/'
    form_class = PersonaForm

    def form_valid(self, form):
        form.instance.modificado_por = self.request.user

        if form.instance.otros_documentos and form.instance.dni:
            messages.add_message(self.request, messages.WARNING, f'Solo se puedes añadir un campo "dni" o "otros documentos"  ')
            return redirect('adra:persona-create')

        documentacion_ben = form.instance.dni if form.instance.dni else form.instance.otros_documentos
        dele = DelegacionData.objects.all().first()

        # find_ben = BeneficiariosGlobales.objects.filter(documentacion_beneficiario__contains=form.instance.dni,telefono=form.instance.telefono)
        find_ben = BeneficiariosGlobales.objects.filter(
            Q(documentacion_beneficiario__icontains=documentacion_ben) | Q(telefono=form.instance.telefono))

        if find_ben.count() > 0:
            print(find_ben)
            try:
                find = [f for f in find_ben][0]
                print(find)
                messages.add_message(self.request, messages.WARNING,
                                     f'Beneficiario ya existe en otra delegación! <br> -- <b style="color:red">delegación</b>: {find.delegacion_name} <br> -- <b style="color:red">ciudad</b>:{find.ciudad} <br> -- <b style="color:red">provincia</b>:{find.provincia} ')
            except Exception:
                print("no exite datos de este beneficiario")

            return redirect('adra:persona-create')
        else:
            print("beneficiarul no existe")
            ben_global = BeneficiariosGlobales(delegacion_name=dele.nombre,
                                               nombre_beneficiario=form.instance.nombre_apellido,
                                               documentacion_beneficiario=documentacion_ben,
                                               ciudad=dele.ciudad,
                                               provincia=dele.provincia,
                                               telefono=form.instance.telefono,
                                               )
            ben_global.save()
            messages.add_message(self.request, messages.SUCCESS, f'Beneficiario añadido correctamente!')
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            p = Persona.objects.latest('created_at')
            context['nbar'] = "create"
            context['bas'] = p
            return context
        except Persona.DoesNotExist:
            pass


class PersonaUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Persona
    fields = [
        'nombre_apellido',
        'dni',
        'otros_documentos',
        'fecha_nacimiento',
        'numero_adra',
        'nacionalidad',
        'domicilio',
        'are_acte',
        'ciudad',
        'telefono',
        'mensaje',
        'sexo',
        'discapacidad',
        'domingo',
        'empadronamiento',
        'libro_familia',
        'fotocopia_dni',
        'prestaciones',
        'nomnia',
        'cert_negativo',
        'aquiler_hipoteca',
        'recibos',
        'email',
        'covid'
    ]
    success_message = 'Datele sau salvat cu success!!'

    def form_valid(self, form):
        form.instance.modificado_por = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['up'] = "update"
        return context


class PersonaDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Persona
    success_message = 'Beneficirio borrado corectamente'
    success_url = '/'


def adauga_alimentos_persona(request, pk):
    persona = get_object_or_404(Persona, pk=pk)
    almacen = AlmacenAlimentos.objects.get(pk=1)

    if request.method == 'POST':
        a_form = AlimentosFrom(request.POST)
        if a_form.is_valid():
            alimentos = a_form.save(commit=False)

            almacen.alimento_1 -= alimentos.alimento_1
            almacen.alimento_2 -= alimentos.alimento_2
            almacen.alimento_3 -= alimentos.alimento_3
            almacen.alimento_4 -= alimentos.alimento_4
            # almacen.alimento_5 -= alimentos.alimento_5
            almacen.alimento_6 -= alimentos.alimento_6
            almacen.alimento_7 -= alimentos.alimento_7
            almacen.alimento_8 -= alimentos.alimento_8
            almacen.alimento_9 -= alimentos.alimento_9
            almacen.alimento_10 -= alimentos.alimento_10
            almacen.alimento_11 -= alimentos.alimento_11
            almacen.alimento_12 -= alimentos.alimento_12
            almacen.alimento_13 -= alimentos.alimento_13
            almacen.alimento_14 -= alimentos.alimento_14
            almacen.alimento_15 -= alimentos.alimento_15

            alimentos.persona = persona
            alimentos.modificado_por = request.user
            almacen.save()
            alimentos.save()
            # logger.warning("aliemnte sau dat beneficiarului")
            messages.success(request, 'Los alimentos se han entregado correctamente!')
            return redirect(persona)

    else:
        a_form = AlimentosFrom()
    return render(request, 'adra/alimentos_form.html', {'form': a_form})


class PersonaAlimentosUpdateView(LoginRequiredMixin, UpdateView):
    model = Alimentos
    fields = [
        'alimento_1',
        'alimento_2',
        'alimento_3',
        'alimento_4',
        'alimento_6',
        'alimento_7',
        'alimento_8',
        'alimento_9',
        'alimento_10',
        'alimento_11',
        'alimento_12',

adra/templates/statistics/index.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}


{% block title %}
    Adra-Statistics
{% endblock %}

{% block content %}
    <a class="btn btn-info mb-3" href="{% url 'adra:exportar-users-csv' %}">Exportar beneficiarios</a>
{#    <a class="btn btn-info mb-3" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"#}
{#       aria-controls="collapseExample">Exportar valoracion social</a>#}
{#    <div class="collapse" id="collapseExample">#}
{#        <div class="card card-body">#}
{##}
{#            <div class="row">#}
{#                <div class="col-md-6 col-sm-12  ">#}
{#                    <form action="{% url 'adra:statistics-personas' %}" method="post">#}
{#                        {% csrf_token %}#}
{#                        <label for="dom_se" style="font-size: 25px;">Seleciona fecha para generar las valoraciones#}
{#                            sociales:#}
{#                        </label>#}
{#                        <input required type="date" name="fecha_val" id=""><br>#}
{#                        <input type="submit" value="Generar" class="btn btn-outline btn-success mt-4">#}
{#                    </form>#}
{#                </div>#}
{#            </div>#}
{##}
{#        </div>#}
{#    </div>#}




    <table class="table table-striped">
        <thead class="thead-dark">
        <tr>
            <th scope="col"></th>
            <th scope="col">0 a 2</th>
            <th scope="col">3 a 15</th>
            <th scope="col">16-64</th>
            <th scope="col">+ de 65</th>
            <th scope="col">Total</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">Mujeres</th>
            <td>{{ total_per_mujer_02 }}</td>
            <td>{{ total_per_mujer_03 }}</td>
            <td>{{ total_per_mujer_16 }}</td>
            <td>{{ total_per_mujer_65 }}</td>
            <td>{{ total_mujeres }}</td>
        </tr>
        <tr>
            <th scope="row">Hombres</th>
            <td>{{ total_per_hombre_02 }}</td>
            <td>{{ total_per_hombre_03 }}</td>
            <td>{{ total_per_hombre_16 }}</td>
            <td>{{ total_per_hombre_65 }}</td>
            <td>{{ total_hombres }}</td>
        </tr>
        <tr>
            <th scope="row">Total</th>
            <td>{{ total_02 }}</td>
            <td>{{ total_03 }}</td>
            <td>{{ total_16 }}</td>
            <td>{{ total_65 }}</td>
            <td>{{ total_personas }}</td>
        </tr>
        </tbody>
    </table>
    <br>
    <div class="row">
        <div class="col-md-4">
            <h5>Personas con Discapacidad</h5>
            <table class="table table-dark">
                <thead>
                <tr>
                    <th scope="col">Discapacidad</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">{{ discapacidad }}</th>

                </tr>

                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <h5>Beneficiarios</h5>
            <table class="table table-dark">
                <thead>
                <tr>
                    <th scope="col">Total Beneficiarios</th>
                    <th scope="col">Total Familiares</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">{{ total_beneficiarios }}</th>
                    <th scope="row">{{ total_familiares }}</th>

                </tr>

                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <h5>Conteo con</h5>
            <form action="{% url 'adra:statistics-personas' %}" method="post">
             {% csrf_token %}
                <div class="form-row align-items-center">
                    <div class="col-auto my-1">
                        <label class="mr-sm-4 sr-only" for="inlineFormCustomSelect">Preference</label>
                        <select class="custom-select mr-sm-4" name="mod" id="inlineFormCustomSelect">

                            <option  {% if mod == 1 %} selected   {% endif %} value="1">Sin covid</option>
                            <option  {% if mod == 2 %} selected   {% endif %} value="2">Con covid</option>


                        </select>
                    </div>
                    <div class="col-auto my-1">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h1 class="text-center pt-5">Registros por años</h1>
            <div id="main" style="width:100%; height:400px;"></div>
        </div>
    </div>

{% endblock content %}
{% block script %}
    <script>
        // based on prepared DOM, initialize echarts instance
        var myChart = echarts.init(document.getElementById('main'));


        option = {
            tooltip: {
                trigger: 'item',
                formatter: '{c} registros'
            },
            xAxis: {
                type: 'category',
                data: ['2018', '2019', '2020','2021',]
            },
            yAxis: {
                type: 'value'
            },
        };


        axios.get("{% url 'adra:get_data' %}")
            .then(function (response) {
                console.log(response);
                myChart.setOption({
                    series: [{
                        data: response.data.reg,
                        type: 'line'
                    }]
                });
            })
            .catch(function (error) {
                console.log(error);
            })


        // use configuration item and data specified to show chart
        myChart.setOption(option);
        window.onresize = function () {
            myChart.resize();
        };
    </script>

{% endblock %}